services:
  postgres:
    image: postgres:16-alpine
    container_name: relay
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: relay_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d relay']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
