export enum AuditAction {
  AUTH_LOGIN_SUCCEEDED = 'auth.login.succeeded',
  AUTH_LOGOUT_SUCCEEDED = 'auth.logout.succeeded',
  AUTH_REFRESH_FAILED = 'auth.refresh.failed',
  AUTH_EMAIL_VERIFIED = 'auth.email.verified',
  WORKSPACE_CREATED = 'workspace.created',
  WORKSPACE_PROFILE_UPDATED = 'workspace.profile.updated',
  WORKSPACE_INVITE_CREATED = 'workspace.invite.created',
  WORKSPACE_INVITE_REVOKED = 'workspace.invite.revoked',
  WORKSPACE_INVITE_ACCEPTED = 'workspace.invite.accepted',
  WORKSPACE_MEMBER_ROLE_UPDATED = 'workspace.member.role.updated',
  WORKSPACE_MEMBER_REMOVED = 'workspace.member.removed',
  WORKSPACE_MEMBER_LEFT = 'workspace.member.left',
  WORKSPACE_OWNERSHIP_TRANSFERRED = 'workspace.ownership.transferred',
  WORKSPACE_STATUS_UPDATED = 'workspace.status.updated',
  WORKSPACE_SOFT_DELETE_UPDATED = 'workspace.soft_delete.updated',
  WORKSPACE_RESTORED = 'workspace.restored',
  WORKSPACE_INVITE_REVOKED_BY_ADMIN = 'workspace.invite.revoked.by_admin',
  WORKSPACE_MEMBER_REVOKED_BY_ADMIN = 'workspace.member.revoked.by_admin',
  PERMISSION_PLATFORM_UPDATED = 'permission.platform.updated',
  PERMISSION_PLATFORM_BULK_UPDATED = 'permission.platform.bulk_updated',
  PERMISSION_WORKSPACE_UPDATED = 'permission.workspace.updated',
  PERMISSION_WORKSPACE_BULK_UPDATED = 'permission.workspace.bulk_updated',
}

export enum AuditEntityType {
  USER = 'user',
  SESSION = 'session',
  WORKSPACE = 'workspace',
  WORKSPACE_INVITE = 'workspace_invite',
  WORKSPACE_MEMBER = 'workspace_member',
  PERMISSION_POLICY = 'permission_policy',
}
