export enum AuditAction {
  AUTH_LOGIN_SUCCEEDED = 'auth.login.succeeded',
  AUTH_LOGOUT_SUCCEEDED = 'auth.logout.succeeded',
  AUTH_REFRESH_FAILED = 'auth.refresh.failed',
  AUTH_EMAIL_VERIFIED = 'auth.email.verified',
  ORGANIZATION_CREATED = 'workspace.created',
  ORGANIZATION_PROFILE_UPDATED = 'workspace.profile.updated',
  ORGANIZATION_INVITE_CREATED = 'workspace.invite.created',
  ORGANIZATION_INVITE_REVOKED = 'workspace.invite.revoked',
  ORGANIZATION_INVITE_ACCEPTED = 'workspace.invite.accepted',
  ORGANIZATION_MEMBER_ROLE_UPDATED = 'workspace.member.role.updated',
  ORGANIZATION_MEMBER_REMOVED = 'workspace.member.removed',
  ORGANIZATION_MEMBER_LEFT = 'workspace.member.left',
  ORGANIZATION_OWNERSHIP_TRANSFERRED = 'workspace.ownership.transferred',
  ORGANIZATION_STATUS_UPDATED = 'workspace.status.updated',
  ORGANIZATION_SOFT_DELETE_UPDATED = 'workspace.soft_delete.updated',
  ORGANIZATION_RESTORED = 'workspace.restored',
  ORGANIZATION_INVITE_REVOKED_BY_ADMIN = 'workspace.invite.revoked.by_admin',
  ORGANIZATION_MEMBER_REVOKED_BY_ADMIN = 'workspace.member.revoked.by_admin',
  PERMISSION_PLATFORM_UPDATED = 'permission.platform.updated',
  PERMISSION_PLATFORM_BULK_UPDATED = 'permission.platform.bulk_updated',
  PERMISSION_ORGANIZATION_UPDATED = 'permission.workspace.updated',
  PERMISSION_ORGANIZATION_BULK_UPDATED = 'permission.workspace.bulk_updated',
}

export enum AuditEntityType {
  USER = 'user',
  SESSION = 'session',
  ORGANIZATION = 'workspace',
  ORGANIZATION_INVITE = 'workspace_invite',
  ORGANIZATION_MEMBER = 'workspace_member',
  PERMISSION_POLICY = 'permission_policy',
}
