export enum AuditAction {
  AUTH_LOGIN_SUCCEEDED = 'auth.login.succeeded',
  AUTH_LOGOUT_SUCCEEDED = 'auth.logout.succeeded',
  AUTH_REFRESH_FAILED = 'auth.refresh.failed',
  AUTH_EMAIL_VERIFIED = 'auth.email.verified',
  WORKSPACE_CREATED = 'workspace.created',
  WORKSPACE_PROFILE_UPDATED = 'workspace.profile.updated',
  WORKSPACE_INVITE_CREATED = 'workspace.invite.created',
  WORKSPACE_INVITE_REVOKED = 'workspace.invite.revoked',
  WORKSPACE_INVITE_ACCEPTED = 'workspace.invite.accepted',
  WORKSPACE_MEMBER_ROLE_UPDATED = 'workspace.member.role.updated',
  WORKSPACE_MEMBER_REMOVED = 'workspace.member.removed',
  WORKSPACE_MEMBER_LEFT = 'workspace.member.left',
  WORKSPACE_OWNERSHIP_TRANSFERRED = 'workspace.ownership.transferred',
  WORKSPACE_STATUS_UPDATED = 'workspace.status.updated',
  WORKSPACE_SOFT_DELETE_UPDATED = 'workspace.soft_delete.updated',
  WORKSPACE_RESTORED = 'workspace.restored',
  WORKSPACE_INVITE_REVOKED_BY_ADMIN = 'workspace.invite.revoked.by_admin',
  WORKSPACE_MEMBER_REVOKED_BY_ADMIN = 'workspace.member.revoked.by_admin',
  WORKSPACE_CHANNEL_CREATED = 'workspace.channel.created',
  WORKSPACE_CHANNEL_UPDATED = 'workspace.channel.updated',
  WORKSPACE_CHANNEL_ARCHIVED = 'workspace.channel.archived',
  WORKSPACE_CHANNEL_JOINED = 'workspace.channel.joined',
  WORKSPACE_CHANNEL_LEFT = 'workspace.channel.left',
  WORKSPACE_CHANNEL_MEMBER_ADDED = 'workspace.channel.member.added',
  WORKSPACE_CHANNEL_MEMBER_REMOVED = 'workspace.channel.member.removed',
  WORKSPACE_MESSAGE_CREATED = 'workspace.message.created',
  WORKSPACE_MESSAGE_UPDATED = 'workspace.message.updated',
  WORKSPACE_MESSAGE_DELETED = 'workspace.message.deleted',
  WORKSPACE_MESSAGE_THREAD_REPLY_CREATED = 'workspace.message.thread.reply.created',
  WORKSPACE_MESSAGE_THREAD_REPLY_UPDATED = 'workspace.message.thread.reply.updated',
  WORKSPACE_MESSAGE_THREAD_REPLY_DELETED = 'workspace.message.thread.reply.deleted',
  WORKSPACE_MESSAGE_READ_UPDATED = 'workspace.message.read.updated',
  PERMISSION_PLATFORM_UPDATED = 'permission.platform.updated',
  PERMISSION_PLATFORM_BULK_UPDATED = 'permission.platform.bulk_updated',
  PERMISSION_WORKSPACE_UPDATED = 'permission.workspace.updated',
  PERMISSION_WORKSPACE_BULK_UPDATED = 'permission.workspace.bulk_updated',
}

export enum AuditEntityType {
  USER = 'user',
  SESSION = 'session',
  WORKSPACE = 'workspace',
  WORKSPACE_INVITE = 'workspace_invite',
  WORKSPACE_MEMBER = 'workspace_member',
  CHANNEL = 'channel',
  CHANNEL_MEMBER = 'channel_member',
  MESSAGE = 'message',
  MESSAGE_ATTACHMENT = 'message_attachment',
  PERMISSION_POLICY = 'permission_policy',
}
